[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
  autoLaunch = true

[[redirects]]
  from = "/jobs/:id"
  to = "/.netlify/functions/job?id=:id"
  status = 200

[[redirects]]
  from = "/jobs/:id/*"
  to = "/404"
  force = false
  status = 404

[[redirects]]
  from = "/jobs"
  to = "/404"
  force = false
  status = 404

# 404 Redirect
[[redirects]]
  from = "/*"
  to = "/404"
  force = false
  status = 404