module.exports = (data) => `
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Title, Description, Keywords-->
        <title>TITLE</title>
        <meta name="description" content="{{ description | default: site.description}}">

        <!-- Favicon-->
        <link rel="shortcut icon" type="image/ico" href="/favicon.ico" />

        <!-- CSS generated by webpack -->
        <link rel="stylesheet" type="text/css" href="/assets/main.css" />
    </head>
    <body>
        <h1>Job id: ${JSON.stringify(data.event)}</h1>
    </body>
</html>
`
